<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sub_member</name>
   <tag></tag>
   <elementGuidId>afe16fa2-57b2-4428-8228-8159045a3047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-center&quot;)/ul[@id=&quot;nav-sub-members&quot;]/li[2]</value>
   </webElementProperties>
</WebElementEntity>
